// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function SingleIcon(Props) {
  var className = Props.className;
  var fillColor = Props.fillColor;
  var tmp = {
    height: "24",
    width: "24",
    preserveAspectRatio: "xMidYMid meet",
    version: "1.0",
    viewBox: "0 0 24.000000 24.000000",
    xmlns: "http://www.w3.org/2000/svg"
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("svg", tmp, React.createElement("g", {
                  fill: fillColor,
                  stroke: "none",
                  transform: "translate(0.000000,24.000000) scale(0.002344,-0.002344)"
                }, React.createElement("path", {
                      d: "M3330 8478 c-36 -5 -104 -22 -151 -38 -48 -17 -96 -30 -108 -30 -57\n0 -373 -321 -384 -390 -3 -19 -21 -75 -39 -125 l-33 -90 -3 -892 -2 -893 589\n0 589 0 3 245 c3 178 7 247 17 257 6 6 12 25 12 42 0 104 184 286 288 286 17\n0 34 5 37 10 9 14 1907 14 1975 -1 31 -7 50 -16 50 -25 0 -9 10 -14 28 -14 32\n0 102 -44 102 -65 0 -8 7 -15 15 -15 18 0 75 -76 75 -101 0 -9 5 -19 10 -21 6\n-2 18 -23 27 -48 13 -35 17 -99 21 -297 l4 -253 589 0 589 0 0 858 c0 558 -4\n879 -11 918 -5 32 -21 88 -35 124 -13 36 -24 73 -24 83 0 9 -4 17 -9 17 -9 0\n-61 85 -61 100 0 4 -18 26 -40 48 -22 22 -40 49 -40 61 0 13 -6 21 -16 21 -22\n0 -94 58 -94 76 0 8 -9 14 -20 14 -21 0 -100 47 -100 60 0 4 -15 10 -33 13\n-18 3 -53 14 -78 25 -116 53 -85 52 -1949 51 -992 -1 -1753 -5 -1790 -11z"
                    }), React.createElement("path", {
                      d: "M2075 5495 c-5 -1 -44 -8 -85 -15 -228 -38 -483 -245 -587 -478 -14\n-31 -31 -64 -38 -72 -22 -26 -27 -105 -31 -577 l-5 -463 3791 0 3790 0 0 438\nc0 347 -3 449 -15 497 -8 33 -14 72 -15 88 0 15 -4 27 -8 27 -9 0 -52 98 -52\n118 0 6 -4 12 -8 12 -13 0 -62 80 -62 101 0 10 -6 19 -13 19 -16 0 -87 72 -87\n88 0 7 -5 12 -11 12 -18 0 -99 63 -99 77 0 7 -9 13 -21 13 -18 0 -96 36 -109\n50 -3 3 -34 15 -70 25 -36 10 -68 24 -72 30 -5 7 -955 11 -3095 12 -1698 1\n-3092 0 -3098 -2z"
                    }), React.createElement("path", {
                      d: "M1330 2990 l0 -380 405 0 c263 0 405 -3 405 -10 0 -5 9 -10 20 -10\n20 0 20 -7 20 -420 l0 -420 165 0 165 0 0 430 0 430 2610 0 2610 0 0 -430 0\n-430 165 0 165 0 0 413 c0 388 1 415 18 430 17 15 61 17 425 17 l407 0 0 380\n0 380 -3790 0 -3790 0 0 -380z"
                    })));
}

var make = SingleIcon;

export {
  make ,
  
}
/* react Not a pure module */
