// Generated by ReScript, PLEASE EDIT WITH CARE


var Button = {};

var Items = {};

var Item = {};

var Menu = {
  Button: Button,
  Items: Items,
  Item: Item
};

var Overlay = {};

var Title = {};

var Description = {};

var Dialog = {
  Overlay: Overlay,
  Title: Title,
  Description: Description
};

export {
  Menu ,
  Dialog ,
  
}
/* No side effect */
