// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var saveKey = "ZawgyiUnicodeConverter_SaveLastInput";

function useSaveLstInput(initialText) {
  var match = React.useState(function () {
        try {
          var v = localStorage.getItem(saveKey);
          if (v !== null && v.length !== 0) {
            return v;
          } else {
            return initialText;
          }
        }
        catch (exn){
          return initialText;
        }
      });
  var setStoredText = match[1];
  var saveText = function (text) {
    try {
      localStorage.setItem(saveKey, text);
      Curry._1(setStoredText, (function (_prev) {
              return text;
            }));
      return ;
    }
    catch (raw_e){
      var e = Caml_js_exceptions.internalToOCamlException(raw_e);
      if (e.RE_EXN_ID === Js_exn.$$Error) {
        var msg = e._1.message;
        if (msg !== undefined) {
          console.log(msg);
          return ;
        } else {
          return ;
        }
      }
      throw e;
    }
  };
  return [
          match[0],
          saveText
        ];
}

export {
  saveKey ,
  useSaveLstInput ,
  
}
/* react Not a pure module */
