// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ActionBar from "../components/ActionBar.js";
import * as Converter from "rescript-unicode-zawgyi-converter/src/converter.js";

function string(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

function useRef(prim) {
  return React.useRef(prim);
}

function useEffect0(prim) {
  React.useEffect((function () {
          return Curry._1(prim, undefined);
        }), []);
  
}

var zawgyiText = "စာရုိက္ရန္";

function Home(Props) {
  var zawgyiInputRef = React.useRef(null);
  var unicodeInputRef = React.useRef(null);
  var match = React.useState(function () {
        return /* Zawgyi */0;
      });
  var setSelectedTextArea = match[1];
  var selectedTextArea = match[0];
  var x = "tab-btn border-b-2 border-primary_700";
  var y = "tab-btn";
  var match$1 = selectedTextArea ? [
      y,
      x
    ] : [
      x,
      y
    ];
  var x$1 = "w-full h-full p-[0.8rem] pt-0";
  var y$1 = "hidden h-full p-[0.8rem] pt-0";
  var match$2 = selectedTextArea ? [
      y$1,
      x$1
    ] : [
      x$1,
      y$1
    ];
  React.useEffect((function () {
          var input = zawgyiInputRef.current;
          if (!(input == null)) {
            input.value = zawgyiText;
          }
          var input$1 = unicodeInputRef.current;
          if (!(input$1 == null)) {
            input$1.value = Converter.zg2uni(zawgyiText);
          }
          
        }), []);
  var handleZawgyiBtnClick = function (e) {
    e.preventDefault();
    return Curry._1(setSelectedTextArea, (function (param) {
                  return /* Zawgyi */0;
                }));
  };
  var handleUnicodeBtnClick = function (e) {
    e.preventDefault();
    return Curry._1(setSelectedTextArea, (function (param) {
                  return /* Unicode */1;
                }));
  };
  var handleZawgyiTextChange = function (e) {
    var value = e.target.value;
    var input = unicodeInputRef.current;
    if (!(input == null)) {
      input.value = Converter.zg2uni(value);
      return ;
    }
    
  };
  var handleUnicodeTextChange = function (e) {
    var value = e.target.value;
    var input = zawgyiInputRef.current;
    if (!(input == null)) {
      input.value = Converter.uni2zg(value);
      return ;
    }
    
  };
  return React.createElement("div", {
              className: "flex flex-col flex-nowrap h-[calc(100vh-3rem)] w-full"
            }, React.createElement("div", {
                  className: "flex flex-nowrap w-full h-10 items-end bg-white"
                }, React.createElement("div", {
                      className: "flex px-3 pb-1 space-x-2 items-end font-secondary"
                    }, React.createElement("button", {
                          className: match$1[0],
                          type: "button",
                          onClick: handleZawgyiBtnClick
                        }, "Zawgyi"), React.createElement("button", {
                          className: match$1[1],
                          type: "button",
                          onClick: handleUnicodeBtnClick
                        }, "Unicode")), React.createElement(ActionBar.make, {
                      className: "flex p-1 pr-3 space-x-2 justify-end ml-auto w-36"
                    })), React.createElement("div", {
                  className: "flex h-[calc(100vh-5.5rem)]"
                }, React.createElement("div", {
                      className: match$2[0]
                    }, React.createElement("textarea", {
                          ref: zawgyiInputRef,
                          className: "text-area w-full font-myanmar_zawgyi",
                          onChange: handleZawgyiTextChange
                        })), React.createElement("div", {
                      className: match$2[1]
                    }, React.createElement("textarea", {
                          ref: unicodeInputRef,
                          className: "text-area w-full font-myanmar_unicode",
                          onChange: handleUnicodeTextChange
                        }))));
}

var make = Home;

export {
  string ,
  useState ,
  useRef ,
  useEffect0 ,
  zawgyiText ,
  make ,
  
}
/* react Not a pure module */
