// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TrashButton from "./TrashButton.js";
import * as CopyMenuButton from "./CopyMenuButton.js";
import * as LayoutToggleButton from "./LayoutToggleButton.js";

function ActionBar(Props) {
  var className = Props.className;
  var tmp = {};
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("div", tmp, React.createElement(TrashButton.make, {
                  className: "h-8 w-8",
                  onClick: (function (e) {
                      console.log(e.target);
                      
                    })
                }), React.createElement(CopyMenuButton.make, {
                  className: "h-8 w-8",
                  onCopyZawgyiText: (function (e) {
                      console.log(e.target);
                      
                    }),
                  onCopyUnicodeText: (function (e) {
                      console.log(e.target);
                      
                    }),
                  onCopyBoth: (function (e) {
                      console.log(e.target);
                      
                    })
                }), React.createElement(LayoutToggleButton.make, {
                  className: "hidden md:block h-8 w-8",
                  toggleStatus: /* Single */0,
                  onClick: (function (e) {
                      console.log(e.target);
                      
                    })
                }));
}

var make = ActionBar;

export {
  make ,
  
}
/* react Not a pure module */
