// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Rabbit$UnicodeToZawgyi from "../Rabbit.bs.js";

function string(prim) {
  return prim;
}

function useState(prim) {
  return React.useState(function () {
              return Curry._1(prim, undefined);
            });
}

var unicodeSampleText = "༺ လယ်တီဆရာတော်ဘုရားကြီးရေးသားတော်မူသော ༻\n\n  ☸ နိဗ္ဗိန္နတေးထပ် ☸\n ༺༻༺༻༺༻\nအဝိဇ္ဇာ ပိတ်ကာဆို့၊\nမိစ္ဆာမြို့ပြင်ပြင်၊\nဣဋ္ဌာလို့ ခင်မင်လျှင်၊\nလွင့်စင်မည်မလွဲ၊\nအရွတ်စု အပုတ်ကောင်ကို၊\nအဟုတ်ယောင် မှားဖို့ ဖန်နဲ။\n\nအသုဘ ရုပ်တစ္ဆေငယ်၊\nမဟုတ်လေ ကိုယ်ထဲ၊\nအပုပ်ရေ စိုတရွှဲဟာမို့၊\nယိုမစဲ သူ့မှာ၊\nသွေးသည်းချေ ပြည် သလိပ်တွေက၊\nတည်မဆိတ် လျှမ်းပြည့်သည်သာ၊\n\nသို့ကလောက် ရွံစရာကို၊\nလွန်တဏှာ မက်စွဲပါလို့၊\nစက်ဝဲမှာတပေပေ၊\nမွန်းကြပလေ၊\nတဏှာဖမ်းတဲ့ အကန်းတွေမှာ၊\nအပန်းမပြေ ဟိုက်မောရှာကြလေး။\nတဏှာပူးတဲ့ အရူးတွေမှာ\nအမူးမပြေ မိုက်မောရှာကြလေး။\nတဏှာလိုက်တဲ့ အမိုက်တွေမှာ၊\nအဟိုက်မပြေ ပင်ပန်းရှာကြလေး။";

function App$TextArea(Props) {
  var fontFamily = Props.fontFamily;
  var value = Props.value;
  var height = Props.height;
  var show = Props.show;
  var onFocusOpt = Props.onFocus;
  var onKeyUpOpt = Props.onKeyUp;
  var onKeyDownOpt = Props.onKeyDown;
  var onChange = Props.onChange;
  var onFocus = onFocusOpt !== undefined ? onFocusOpt : (function (param) {
        
      });
  var onKeyUp = onKeyUpOpt !== undefined ? onKeyUpOpt : (function (param) {
        
      });
  var onKeyDown = onKeyDownOpt !== undefined ? onKeyDownOpt : (function (param) {
        
      });
  var display = show !== undefined && show ? "block" : "none";
  var style = height !== undefined ? ({
        display: display,
        fontFamily: fontFamily,
        height: height
      }) : ({
        display: display,
        fontFamily: fontFamily
      });
  return React.createElement("textarea", {
              className: "text-area",
              style: style,
              value: value,
              onKeyDown: onKeyDown,
              onKeyUp: onKeyUp,
              onFocus: onFocus,
              onChange: onChange
            });
}

var TextArea = {
  make: App$TextArea
};

var unicodeFontName = "\"Noto Sans Myanmar\",\"Pyidaungsu\"";

var zawgyiFontName = "Noto Sans Zawgyi";

var mobileHeight = "calc(100vh - 8.5em)";

function getLgLabelaClass(selected) {
  return (
            selected ? "border-primary_200 text-primary_200" : "border-primary_500 text-primary_500"
          ).concat(" font-bold border-b-2 pb-1  inline self-start px-2 focus:outline-none");
}

function getTabLabelClass(selected) {
  return (
            selected ? "border-primary_200 text-primary_200" : "border-transparent text-primary_500 hover:text-primary_400 hover:border-primary_500"
          ).concat(" whitespace-nowrap py-2 px-1 border-b-2 font-bold");
}

function App(Props) {
  var match = React.useState(function () {
        return "theme-gray";
      });
  var match$1 = React.useState(function () {
        return unicodeSampleText;
      });
  var setUnicodeText = match$1[1];
  var unicodeText = match$1[0];
  var match$2 = React.useState(function () {
        return Rabbit$UnicodeToZawgyi.uni2zg(unicodeSampleText);
      });
  var setZawgyiText = match$2[1];
  var zawgyiText = match$2[0];
  var match$3 = React.useState(function () {
        return "Unicode";
      });
  var setSelectedTab = match$3[1];
  var selectedTab = match$3[0];
  var match$4 = React.useState(function () {
        return "Unicode";
      });
  var setFocusedLgTextArea = match$4[1];
  var focusedLgTextArea = match$4[0];
  var handleUnicodeTextChange = function (e) {
    var newValue = e.target.value;
    Curry._1(setUnicodeText, (function (param) {
            return newValue;
          }));
    return Curry._1(setZawgyiText, (function (param) {
                  return Rabbit$UnicodeToZawgyi.uni2zg(newValue);
                }));
  };
  var handleZawgyiTextChange = function (e) {
    var newValue = e.target.value;
    Curry._1(setZawgyiText, (function (param) {
            return newValue;
          }));
    return Curry._1(setUnicodeText, (function (param) {
                  return Rabbit$UnicodeToZawgyi.zg2uni(newValue);
                }));
  };
  return React.createElement("div", {
              className: "" + match[0] + " h-screen"
            }, React.createElement("div", {
                  className: "hidden 2xl:flex flex-row space-x-5 p-10 pt-12 bg-primary_700 justify-between",
                  id: "lg-screen",
                  style: {
                    height: "calc(100vh - 1.5em)"
                  }
                }, React.createElement("div", {
                      className: "flex flex-col flex-1 space-y-4 self-stretch"
                    }, React.createElement("span", {
                          className: getLgLabelaClass(focusedLgTextArea === "Unicode")
                        }, "Unicode"), React.createElement(App$TextArea, {
                          fontFamily: unicodeFontName,
                          value: unicodeText,
                          show: true,
                          onFocus: (function (e) {
                              return Curry._1(setFocusedLgTextArea, (function (param) {
                                            return "Unicode";
                                          }));
                            }),
                          onChange: handleUnicodeTextChange
                        })), React.createElement("div", {
                      className: "flex flex-col flex-1 space-y-4 self-stretch"
                    }, React.createElement("span", {
                          className: getLgLabelaClass(focusedLgTextArea === "Zawgyi")
                        }, "Zawgyi"), React.createElement(App$TextArea, {
                          fontFamily: zawgyiFontName,
                          value: zawgyiText,
                          show: true,
                          onFocus: (function (e) {
                              return Curry._1(setFocusedLgTextArea, (function (param) {
                                            return "Zawgyi";
                                          }));
                            }),
                          onChange: handleZawgyiTextChange
                        }))), React.createElement("div", {
                  className: "2xl:hidden flex flex-col p-4 pt-12 bg-primary_700",
                  id: "non-lg-screen"
                }, React.createElement("div", {
                      className: "space-x-10 pb-2"
                    }, React.createElement("a", {
                          className: getTabLabelClass(selectedTab === "Unicode"),
                          href: "#",
                          onClick: (function (param) {
                              return Curry._1(setSelectedTab, (function (param) {
                                            return "Unicode";
                                          }));
                            })
                        }, "Unicode"), React.createElement("a", {
                          className: getTabLabelClass(selectedTab === "Zawgyi"),
                          href: "#",
                          onClick: (function (param) {
                              return Curry._1(setSelectedTab, (function (param) {
                                            return "Zawgyi";
                                          }));
                            })
                        }, "Zawgyi")), React.createElement("div", {
                      className: "pt-4"
                    }, React.createElement(App$TextArea, {
                          fontFamily: unicodeFontName,
                          value: unicodeText,
                          height: mobileHeight,
                          show: selectedTab === "Unicode",
                          onChange: handleUnicodeTextChange
                        }), React.createElement(App$TextArea, {
                          fontFamily: zawgyiFontName,
                          value: zawgyiText,
                          height: mobileHeight,
                          show: selectedTab === "Zawgyi",
                          onChange: handleZawgyiTextChange
                        }))), React.createElement("footer", {
                  className: "flex flex-row justify-between px-4 2xl:px-10 bg-primary_800 text-primary_400"
                }, React.createElement("div", {
                      className: "flex-1 self-start"
                    }, React.createElement("a", {
                          className: "text-primary_200 underline",
                          href: "https://github.com/nyinyithann/UnicodeToZawgyi",
                          target: "_blank"
                        }, "GitHub Repo")), React.createElement("div", {
                      className: "flex-1 self-end flex justify-end"
                    }, React.createElement("span", undefined, "Credit: ", React.createElement("a", {
                              className: "text-primary_200 underline",
                              href: "https://github.com/Rabbit-Converter/Rabbit",
                              target: "_blank"
                            }, "Rabbit")))));
}

var initialSelectedTab = "Unicode";

var make = App;

export {
  string ,
  useState ,
  unicodeSampleText ,
  TextArea ,
  unicodeFontName ,
  zawgyiFontName ,
  mobileHeight ,
  initialSelectedTab ,
  getLgLabelaClass ,
  getTabLabelClass ,
  make ,
  
}
/* react Not a pure module */
