// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CopyIcon from "../icons/CopyIcon.js";
import * as React$1 from "@headlessui/react";

function string(prim) {
  return prim;
}

var actionBtnDefaultStyle = "action-btn dark:hover:text-slate_100 dark:hover:bg-slate-300 dark:active:bg-primary_50";

function CopyMenuButton(Props) {
  var className = Props.className;
  var onCopyZawgyiText = Props.onCopyZawgyiText;
  var onCopyUnicodeText = Props.onCopyUnicodeText;
  var onCopyBoth = Props.onCopyBoth;
  var cn = className !== undefined ? "" + actionBtnDefaultStyle + " " + className : actionBtnDefaultStyle;
  return React.createElement(React$1.Menu, {
              as_: "div",
              children: (function (param) {
                  return React.createElement(React.Fragment, undefined, React.createElement(React$1.Menu.Button, {
                                  children: React.createElement("div", {
                                        role: "button",
                                        onClick: (function (e) {
                                            e.preventDefault();
                                            
                                          })
                                      }, React.createElement(CopyIcon.make, {
                                            className: "h-full w-full",
                                            fillColor: "var(--color-primary-600)"
                                          })),
                                  className: cn
                                }), React.createElement(React$1.Menu.Items, {
                                  as_: "div",
                                  children: null,
                                  className: "flex flex-col absolute right-[0.9rem] md:right-[3.2rem] top-[5.4rem] md:top-[5.7rem] origin-top-right w-40 px-2 bg-white border-[1px] border-primary_400 rounded divide-y divide-primary_500 focus:outline-none shadow text-primary_900",
                                  static: param.open
                                }, React.createElement(React$1.Menu.Item, {
                                      children: (function (param) {
                                          return React.createElement("a", {
                                                      href: "",
                                                      onClick: onCopyUnicodeText
                                                    }, "Copy Unicode");
                                        }),
                                      className: "copy-menu-item dark:text-slate-900 dark:hover:text-gray-700"
                                    }), React.createElement(React$1.Menu.Item, {
                                      children: (function (param) {
                                          return React.createElement("a", {
                                                      href: "",
                                                      onClick: onCopyZawgyiText
                                                    }, "Copy Zawgyi");
                                        }),
                                      className: "copy-menu-item dark:text-slate-900 dark:hover:text-gray-700"
                                    }), React.createElement(React$1.Menu.Item, {
                                      children: (function (param) {
                                          return React.createElement("a", {
                                                      href: "",
                                                      onClick: onCopyBoth
                                                    }, "Copy Both");
                                        }),
                                      className: "copy-menu-item dark:text-slate-900 dark:hover:text-gray-700"
                                    })));
                }),
              className: "relative inline-block text-left"
            });
}

var make = CopyMenuButton;

export {
  string ,
  actionBtnDefaultStyle ,
  make ,
  
}
/* react Not a pure module */
