// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Solid from "@heroicons/react/solid";

function Icons$Trash(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  return Solid.TrashIcon({
              className: className,
              onClick: onClick
            });
}

var Trash = {
  make: Icons$Trash
};

function Icons$Copy(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  return Solid.ClipboardCopyIcon({
              className: className,
              onClick: onClick
            });
}

var Copy = {
  make: Icons$Copy
};

function Icons$Settings(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  return Solid.AdjustmentsIcon({
              className: className,
              onClick: onClick
            });
}

var Settings = {
  make: Icons$Settings
};

export {
  Trash ,
  Copy ,
  Settings ,
  
}
/* @heroicons/react/solid Not a pure module */
