// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NavLink from "./NavLink.js";
import * as ThemeMenu from "./ThemeMenu.js";

function string(prim) {
  return prim;
}

function NavBar(Props) {
  return React.createElement("nav", {
              className: "fixed h-12 inset-x-0 z-50 flex-1 px-2 shadow bg-primary_300 \n    shadow-primary_200 dark:bg-slate-600 dark:text-white"
            }, React.createElement("div", {
                  className: "flex items-center justify-between"
                }, React.createElement("div", {
                      className: "flex md:space-x-2 p-2 pl-0 md:p-1 items-center justify-center"
                    }, React.createElement("div", {
                          className: "hidden md:flex mr-4 items-center justify-center font-myanmar_unicode"
                        }, React.createElement("span", {
                              className: "flex-auto text:lg md:text-2xl pt-2 font-bold text-center text-transparent bg-clip-text bg-gradient-to-r from-cyan-600 to-sky-500 dark:text-slate_400"
                            }, "မင်္ဂလာပါ")), React.createElement("div", {
                          className: "flex items-center space-x-4 text-lg font-black font-navigation"
                        }, React.createElement(NavLink.make, {
                              to: "/",
                              children: React.createElement("span", undefined, "Home"),
                              className: "navbar-btn"
                            }), React.createElement(NavLink.make, {
                              to: "/about",
                              children: React.createElement("span", undefined, "About"),
                              className: "navbar-btn"
                            }))), React.createElement("div", {
                      className: "relative flex items-center"
                    }, React.createElement(ThemeMenu.make, {}))));
}

var make = NavBar;

export {
  string ,
  make ,
  
}
/* react Not a pure module */
