// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TrashIcon from "../icons/TrashIcon.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var actionBtnDefaultStyle = "action-btn dark:hover:text-slate_100 dark:hover:bg-slate-300 dark:active:bg-primary_50";

function TrashButton(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  var cn = className !== undefined ? "" + actionBtnDefaultStyle + " " + className : actionBtnDefaultStyle;
  var tmp = {
    className: cn,
    type: "button"
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("button", tmp, React.createElement(TrashIcon.make, {
                  className: "h-full w-full",
                  fillColor: "var(--color-primary-600)"
                }));
}

var make = TrashButton;

export {
  actionBtnDefaultStyle ,
  make ,
  
}
/* react Not a pure module */
